-- 053: Poblar partido_code y delegacion_code en inmuebles existentes
-- Generado automáticamente desde pba_2026_jurisdictions.json

UPDATE inmuebles SET partido_code = '001', delegacion_code = '017' WHERE (partido_id = 'Adolfo Alsina' OR partido_id = 'Adolfo Alsina') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '002', delegacion_code = '008' WHERE (partido_id = 'Alberti' OR partido_id = 'Alberti') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '003', delegacion_code = '005' WHERE (partido_id = 'Almirante Brown' OR partido_id = 'Almirante Brown') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '004', delegacion_code = '005' WHERE (partido_id = 'Avellaneda' OR partido_id = 'Avellaneda') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '005', delegacion_code = '012' WHERE (partido_id = 'Ayacucho' OR partido_id = 'Ayacucho') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '006', delegacion_code = '013' WHERE (partido_id = 'Azul' OR partido_id = 'Azul') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '007', delegacion_code = '007' WHERE (partido_id = 'Bahia Blanca' OR partido_id = 'Bahía Blanca') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '008', delegacion_code = '009' WHERE (partido_id = 'Balcarce' OR partido_id = 'Balcarce') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '009', delegacion_code = '010' WHERE (partido_id = 'Baradero' OR partido_id = 'Baradero') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '010', delegacion_code = '011' WHERE (partido_id = 'Arrecifes' OR partido_id = 'Arrecifes') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '011', delegacion_code = '013' WHERE (partido_id = 'Bolivar' OR partido_id = 'Bolívar') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '012', delegacion_code = '016' WHERE (partido_id = 'Bragado' OR partido_id = 'Bragado') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '013', delegacion_code = '001' WHERE (partido_id = 'Brandsen' OR partido_id = 'Brandsen') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '014', delegacion_code = '003' WHERE (partido_id = 'Campana' OR partido_id = 'Campana') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '015', delegacion_code = '005' WHERE (partido_id = 'Cañuelas' OR partido_id = 'Cañuelas') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '016', delegacion_code = '016' WHERE (partido_id = 'Carlos Casares' OR partido_id = 'Carlos Casares') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '017', delegacion_code = '017' WHERE (partido_id = 'Carlos Tejedor' OR partido_id = 'Carlos Tejedor') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '018', delegacion_code = '008' WHERE (partido_id = 'Carmen De Areco' OR partido_id = 'Carmen de Areco') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '019', delegacion_code = '017' WHERE (partido_id = 'Daireaux' OR partido_id = 'Daireaux') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '020', delegacion_code = '009' WHERE (partido_id = 'Castelli' OR partido_id = 'Castelli') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '021', delegacion_code = '011' WHERE (partido_id = 'Colon' OR partido_id = 'Colón') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '022', delegacion_code = '007' WHERE (partido_id = 'Coronel Dorrego' OR partido_id = 'Coronel Dorrego') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '023', delegacion_code = '007' WHERE (partido_id = 'Coronel Pringles' OR partido_id = 'Coronel Pringles') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '024', delegacion_code = '007' WHERE (partido_id = 'Coronel Suarez' OR partido_id = 'Coronel Suárez') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '025', delegacion_code = '005' WHERE (partido_id = 'Lanus' OR partido_id = 'Lanús') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '026', delegacion_code = '014' WHERE (partido_id = 'Chacabuco' OR partido_id = 'Chacabuco') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '027', delegacion_code = '009' WHERE (partido_id = 'Chascomus' OR partido_id = 'Chascomús') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '028', delegacion_code = '008' WHERE (partido_id = 'Chivilcoy' OR partido_id = 'Chivilcoy') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '029', delegacion_code = '009' WHERE (partido_id = 'Dolores' OR partido_id = 'Dolores') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '030', delegacion_code = '005' WHERE (partido_id = 'Esteban Echeverria' OR partido_id = 'Esteban Echeverría') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '031', delegacion_code = '003' WHERE (partido_id = 'Exaltacion De La Cruz' OR partido_id = 'Exaltación de la Cruz') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '032', delegacion_code = '005' WHERE (partido_id = 'Florencio Varela' OR partido_id = 'Florencio Varela') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '033', delegacion_code = '009' WHERE (partido_id = 'General Alvarado' OR partido_id = 'General Alvarado') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '034', delegacion_code = '013' WHERE (partido_id = 'General Alvear' OR partido_id = 'General Alvear') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '035', delegacion_code = '014' WHERE (partido_id = 'General Arenales' OR partido_id = 'General Arenales') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '036', delegacion_code = '009' WHERE (partido_id = 'General Belgrano' OR partido_id = 'General Belgrano') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '037', delegacion_code = '009' WHERE (partido_id = 'General Guido' OR partido_id = 'General Guido') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '038', delegacion_code = '003' WHERE (partido_id = 'Zarate' OR partido_id = 'Zárate') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '039', delegacion_code = '009' WHERE (partido_id = 'General Madariaga' OR partido_id = 'General Madariaga') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '040', delegacion_code = '013' WHERE (partido_id = 'General La Madrid' OR partido_id = 'General La Madrid') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '041', delegacion_code = '002' WHERE (partido_id = 'General Las Heras' OR partido_id = 'General Las Heras') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '042', delegacion_code = '009' WHERE (partido_id = 'General Lavalle' OR partido_id = 'General Lavalle') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '043', delegacion_code = '009' WHERE (partido_id = 'General Paz' OR partido_id = 'General Paz') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '044', delegacion_code = '014' WHERE (partido_id = 'General Pinto' OR partido_id = 'General Pinto') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '045', delegacion_code = '009' WHERE (partido_id = 'General Pueyrredon' OR partido_id = 'General Pueyrredón') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '046', delegacion_code = '008' WHERE (partido_id = 'General Rodriguez' OR partido_id = 'General Rodríguez') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '047', delegacion_code = '003' WHERE (partido_id = 'General San Martin' OR partido_id = 'General San Martín') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '049', delegacion_code = '014' WHERE (partido_id = 'General Viamonte' OR partido_id = 'General Viamonte') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '050', delegacion_code = '017' WHERE (partido_id = 'General Villegas' OR partido_id = 'General Villegas') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '051', delegacion_code = '015' WHERE (partido_id = 'Adolfo Gonzales Chaves' OR partido_id = 'Adolfo Gonzales Chaves') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '052', delegacion_code = '017' WHERE (partido_id = 'Guamini' OR partido_id = 'Guaminí') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '053', delegacion_code = '012' WHERE (partido_id = 'Benito Juarez' OR partido_id = 'Benito Juárez') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '054', delegacion_code = '014' WHERE (partido_id = 'Junin' OR partido_id = 'Junín') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '055', delegacion_code = '001' WHERE (partido_id = 'La Plata' OR partido_id = 'La Plata') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '056', delegacion_code = '013' WHERE (partido_id = 'Laprida' OR partido_id = 'Laprida') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '057', delegacion_code = '004' WHERE (partido_id = 'Tigre' OR partido_id = 'Tigre') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '058', delegacion_code = '013' WHERE (partido_id = 'Las Flores' OR partido_id = 'Las Flores') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '059', delegacion_code = '014' WHERE (partido_id = 'Leandro N. Alem' OR partido_id = 'Leandro N. Alem') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '060', delegacion_code = '014' WHERE (partido_id = 'Lincoln' OR partido_id = 'Lincoln') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '061', delegacion_code = '015' WHERE (partido_id = 'Loberia' OR partido_id = 'Lobería') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '062', delegacion_code = '005' WHERE (partido_id = 'Lobos' OR partido_id = 'Lobos') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '063', delegacion_code = '005' WHERE (partido_id = 'Lomas De Zamora' OR partido_id = 'Lomas de Zamora') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '064', delegacion_code = '008' WHERE (partido_id = 'Lujan' OR partido_id = 'Luján') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '065', delegacion_code = '001' WHERE (partido_id = 'Magdalena' OR partido_id = 'Magdalena') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '066', delegacion_code = '009' WHERE (partido_id = 'Maipu' OR partido_id = 'Maipú') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '067', delegacion_code = '011' WHERE (partido_id = 'Salto' OR partido_id = 'Salto') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '068', delegacion_code = '002' WHERE (partido_id = 'Marcos Paz' OR partido_id = 'Marcos Paz') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '069', delegacion_code = '009' WHERE (partido_id = 'Mar Chiquita' OR partido_id = 'Mar Chiquita') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '070', delegacion_code = '002' WHERE (partido_id = 'La Matanza' OR partido_id = 'La Matanza') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '071', delegacion_code = '008' WHERE (partido_id = 'Mercedes' OR partido_id = 'Mercedes') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '072', delegacion_code = '002' WHERE (partido_id = 'Merlo' OR partido_id = 'Merlo') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '073', delegacion_code = '001' WHERE (partido_id = 'Monte' OR partido_id = 'Monte') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '074', delegacion_code = '002' WHERE (partido_id = 'Moreno' OR partido_id = 'Moreno') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '075', delegacion_code = '002' WHERE (partido_id = 'Navarro' OR partido_id = 'Navarro') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '076', delegacion_code = '015' WHERE (partido_id = 'Necochea' OR partido_id = 'Necochea') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '077', delegacion_code = '016' WHERE (partido_id = 'Nueve De Julio' OR partido_id = 'Nueve de Julio') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '078', delegacion_code = '013' WHERE (partido_id = 'Olavarria' OR partido_id = 'Olavarría') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '079', delegacion_code = '007' WHERE (partido_id = 'Patagones' OR partido_id = 'Patagones') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '080', delegacion_code = '016' WHERE (partido_id = 'Pehuajo' OR partido_id = 'Pehuajó') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '081', delegacion_code = '017' WHERE (partido_id = 'Pellegrini' OR partido_id = 'Pellegrini') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '082', delegacion_code = '011' WHERE (partido_id = 'Pergamino' OR partido_id = 'Pergamino') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '083', delegacion_code = '009' WHERE (partido_id = 'Pila' OR partido_id = 'Pila') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '084', delegacion_code = '003' WHERE (partido_id = 'Pilar' OR partido_id = 'Pilar') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '085', delegacion_code = '007' WHERE (partido_id = 'Puan' OR partido_id = 'Puan') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '086', delegacion_code = '005' WHERE (partido_id = 'Quilmes' OR partido_id = 'Quilmes') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '087', delegacion_code = '010' WHERE (partido_id = 'Ramallo' OR partido_id = 'Ramallo') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '088', delegacion_code = '012' WHERE (partido_id = 'Rauch' OR partido_id = 'Rauch') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '089', delegacion_code = '017' WHERE (partido_id = 'Rivadavia' OR partido_id = 'Rivadavia') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '090', delegacion_code = '014' WHERE (partido_id = 'Rojas' OR partido_id = 'Rojas') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '091', delegacion_code = '001' WHERE (partido_id = 'Roque Perez' OR partido_id = 'Roque Pérez') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '092', delegacion_code = '007' WHERE (partido_id = 'Saavedra' OR partido_id = 'Saavedra') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '093', delegacion_code = '016' WHERE (partido_id = 'Saladillo' OR partido_id = 'Saladillo') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '094', delegacion_code = '008' WHERE (partido_id = 'San Andres De Giles' OR partido_id = 'San Andrés de Giles') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '095', delegacion_code = '008' WHERE (partido_id = 'San Antonio De Areco' OR partido_id = 'San Antonio de Areco') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '096', delegacion_code = '004' WHERE (partido_id = 'San Fernando' OR partido_id = 'San Fernando') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '097', delegacion_code = '004' WHERE (partido_id = 'San Isidro' OR partido_id = 'San Isidro') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '098', delegacion_code = '010' WHERE (partido_id = 'San Nicolas' OR partido_id = 'San Nicolás') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '099', delegacion_code = '010' WHERE (partido_id = 'San Pedro' OR partido_id = 'San Pedro') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '100', delegacion_code = '005' WHERE (partido_id = 'San Vicente' OR partido_id = 'San Vicente') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '101', delegacion_code = '002' WHERE (partido_id = 'Moron' OR partido_id = 'Morón') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '102', delegacion_code = '008' WHERE (partido_id = 'Suipacha' OR partido_id = 'Suipacha') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '103', delegacion_code = '012' WHERE (partido_id = 'Tandil' OR partido_id = 'Tandil') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '104', delegacion_code = '013' WHERE (partido_id = 'Tapalque' OR partido_id = 'Tapalqué') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '105', delegacion_code = '009' WHERE (partido_id = 'Tordillo' OR partido_id = 'Tordillo') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '106', delegacion_code = '007' WHERE (partido_id = 'Tornquist' OR partido_id = 'Tornquist') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '107', delegacion_code = '017' WHERE (partido_id = 'Trenque Lauquen' OR partido_id = 'Trenque Lauquen') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '108', delegacion_code = '007' WHERE (partido_id = 'Tres Arroyos' OR partido_id = 'Tres Arroyos') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '109', delegacion_code = '016' WHERE (partido_id = 'Veinticinco De Mayo' OR partido_id = 'Veinticinco de Mayo') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '110', delegacion_code = '004' WHERE (partido_id = 'Vicente Lopez' OR partido_id = 'Vicente López') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '111', delegacion_code = '007' WHERE (partido_id = 'Villarino' OR partido_id = 'Villarino') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '113', delegacion_code = '007' WHERE (partido_id = 'Coronel Rosales' OR partido_id = 'Coronel Rosales') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '114', delegacion_code = '001' WHERE (partido_id = 'Berisso' OR partido_id = 'Berisso') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '115', delegacion_code = '001' WHERE (partido_id = 'Ensenada' OR partido_id = 'Ensenada') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '116', delegacion_code = '015' WHERE (partido_id = 'San Cayetano' OR partido_id = 'San Cayetano') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '117', delegacion_code = '003' WHERE (partido_id = 'Tres De Febrero' OR partido_id = 'Tres de Febrero') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '118', delegacion_code = '003' WHERE (partido_id = 'Escobar' OR partido_id = 'Escobar') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '119', delegacion_code = '016' WHERE (partido_id = 'Hipolito Yrigoyen' OR partido_id = 'Hipólito Yrigoyen') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '120', delegacion_code = '005' WHERE (partido_id = 'Berazategui' OR partido_id = 'Berazategui') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '121', delegacion_code = '011' WHERE (partido_id = 'Capitan Sarmiento' OR partido_id = 'Capitán Sarmiento') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '122', delegacion_code = '017' WHERE (partido_id = 'Salliquelo' OR partido_id = 'Salliqueló') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '123', delegacion_code = '009' WHERE (partido_id = 'La Costa' OR partido_id = 'La Costa') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '124', delegacion_code = '009' WHERE (partido_id = 'Pinamar' OR partido_id = 'Pinamar') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '125', delegacion_code = '009' WHERE (partido_id = 'Villa Gesell' OR partido_id = 'Villa Gesell') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '126', delegacion_code = '007' WHERE (partido_id = 'Monte Hermoso' OR partido_id = 'Monte Hermoso') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '127', delegacion_code = '017' WHERE (partido_id = 'Tres Lomas' OR partido_id = 'Tres Lomas') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '128', delegacion_code = '014' WHERE (partido_id = 'Florentino Ameghino' OR partido_id = 'Florentino Ameghino') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '129', delegacion_code = '005' WHERE (partido_id = 'Presidente Peron' OR partido_id = 'Presidente Perón') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '130', delegacion_code = '005' WHERE (partido_id = 'Ezeiza' OR partido_id = 'Ezeiza') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '131', delegacion_code = '002' WHERE (partido_id = 'San Miguel' OR partido_id = 'San Miguel') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '132', delegacion_code = '002' WHERE (partido_id = 'Jose C. Paz' OR partido_id = 'José C. Paz') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '133', delegacion_code = '002' WHERE (partido_id = 'Malvinas Argentinas' OR partido_id = 'Malvinas Argentinas') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '134', delegacion_code = '001' WHERE (partido_id = 'Punta Indio' OR partido_id = 'Punta Indio') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '135', delegacion_code = '002' WHERE (partido_id = 'Hurlingham' OR partido_id = 'Hurlingham') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '136', delegacion_code = '002' WHERE (partido_id = 'Ituzaingo' OR partido_id = 'Ituzaingó') AND (partido_code IS NULL OR partido_code = '');
UPDATE inmuebles SET partido_code = '137', delegacion_code = '009' WHERE (partido_id = 'Lezama' OR partido_id = 'Lezama') AND (partido_code IS NULL OR partido_code = '');

-- Limpiar nomenclaturas que son solo números/códigos entre paréntesis (no son nomenclaturas reales)
-- Ej: "93203 (007), 93204 (007), 93206 (007)" → NULL
-- Ej: "49387" (solo un número) → NULL
-- Preservar nomenclaturas reales como "Circunscripción I, Sección A, Manzana 27..."
UPDATE inmuebles SET nomenclatura = NULL
WHERE nomenclatura ~ '^\s*[\d\s,;/().-]+\s*$'
  AND nomenclatura !~* 'circ|secc|manzana|parcela|lote|fraccion|quinta|chacra';

